"""Scheduler bootstrap: detect whether a tag-driven instance scheduler is
deployed in the account, and generate a lightweight Terraform-native one as
NEW files in the repo (never deployed directly — reviewed and applied through
the user's normal terraform workflow).

Generated files:
- finops-scheduler.tf          — Lambda + EventBridge (15-min) + IAM, with
                                 schedule definitions in a locals map
- finops_scheduler_lambda.py   — the Lambda source: starts/stops EC2/RDS by
                                 parsing their `Schedule` tag against the
                                 definitions passed via env var
"""

from __future__ import annotations

import os
import re
from typing import Any, Optional

SCHEDULE_NAME_RE = re.compile(r"^(mon-fri|daily|sat-sun)-(\d{2})-(\d{2})$")

MANAGED_TF_FILE = "finops-scheduler.tf"
MANAGED_LAMBDA_FILE = "finops_scheduler_lambda.py"
LAMBDA_FUNCTION_NAME = "finops-instance-scheduler"


def parse_schedule_name(name: str) -> Optional[dict[str, Any]]:
    """'mon-fri-07-20' -> {"days": [0..4], "start": 7, "stop": 20}."""
    m = SCHEDULE_NAME_RE.match(name)
    if not m:
        return None
    pattern, start, stop = m.group(1), int(m.group(2)), int(m.group(3))
    if not (0 <= start < stop <= 24):
        return None
    days = {"mon-fri": [0, 1, 2, 3, 4], "daily": [0, 1, 2, 3, 4, 5, 6], "sat-sun": [5, 6]}[pattern]
    return {"days": days, "start": start, "stop": stop}


# --------------------------------------------------------------------------
# Detection (read-only)
# --------------------------------------------------------------------------

def check_scheduler_deployed(region: Optional[str] = None) -> dict[str, Any]:
    """Read-only probe for evidence of a tag-driven scheduler in the account:
    our own Lambda, an EventBridge rule, or an AWS Instance Scheduler stack."""
    mode = os.environ.get("FINOPS_MODE", "auto").lower()
    from .telemetry import _aws_available

    if mode == "mock" or (mode == "auto" and not _aws_available()):
        return {"deployed": False, "source": "mock",
                "note": "mock mode — assuming no scheduler deployed"}

    import boto3
    from botocore.config import Config

    cfg = Config(connect_timeout=5, read_timeout=10, retries={"max_attempts": 1})
    evidence = []
    r = region or "us-east-1"
    try:
        lam = boto3.client("lambda", region_name=r, config=cfg)
        lam.get_function(FunctionName=LAMBDA_FUNCTION_NAME)
        evidence.append(f"lambda function {LAMBDA_FUNCTION_NAME}")
    except Exception:
        pass
    try:
        events = boto3.client("events", region_name=r, config=cfg)
        events.describe_rule(Name=LAMBDA_FUNCTION_NAME)
        evidence.append(f"eventbridge rule {LAMBDA_FUNCTION_NAME}")
    except Exception:
        pass
    try:
        cfn = boto3.client("cloudformation", region_name=r, config=cfg)
        pages = cfn.get_paginator("list_stacks").paginate(
            StackStatusFilter=["CREATE_COMPLETE", "UPDATE_COMPLETE"],
            PaginationConfig={"MaxItems": 300},  # bounded — don't stall the MCP call
        )
        for page in pages:
            for st in page.get("StackSummaries", []):
                if "instance-scheduler" in st.get("StackName", "").lower():
                    evidence.append(f"cloudformation stack {st['StackName']}")
    except Exception:
        pass

    return {"deployed": bool(evidence), "source": "aws", "evidence": evidence}


# --------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------

LAMBDA_SOURCE = '''\"\"\"finops instance scheduler — starts/stops EC2/RDS instances whose
`Schedule` tag matches a window defined in SCHEDULES_JSON.

Generated by finops-mcp. Runs every 15 minutes via EventBridge.
\"\"\"

import datetime
import json
import os

import boto3

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover
    ZoneInfo = None

SCHEDULES = json.loads(os.environ["SCHEDULES_JSON"])
TZ = os.environ.get("SCHEDULER_TZ", "UTC")


def _now():
    if ZoneInfo is not None:
        return datetime.datetime.now(ZoneInfo(TZ))
    return datetime.datetime.utcnow()


def _in_window(sched, now):
    return now.weekday() in sched["days"] and sched["start"] <= now.hour < sched["stop"]


def handler(event, context):
    now = _now()
    actions = []

    ec2 = boto3.client("ec2")
    pages = ec2.get_paginator("describe_instances").paginate(
        Filters=[{"Name": "tag-key", "Values": ["Schedule"]}]
    )
    for page in pages:
        for res in page["Reservations"]:
            for inst in res["Instances"]:
                tags = {t["Key"]: t["Value"] for t in inst.get("Tags", [])}
                sched = SCHEDULES.get(tags.get("Schedule", ""))
                if not sched:
                    continue
                state = inst["State"]["Name"]
                iid = inst["InstanceId"]
                if _in_window(sched, now) and state == "stopped":
                    ec2.start_instances(InstanceIds=[iid])
                    actions.append(f"start ec2 {iid}")
                elif not _in_window(sched, now) and state == "running":
                    ec2.stop_instances(InstanceIds=[iid])
                    actions.append(f"stop ec2 {iid}")

    rds = boto3.client("rds")
    for page in rds.get_paginator("describe_db_instances").paginate():
        for db in page["DBInstances"]:
            arn = db["DBInstanceArn"]
            tags = {t["Key"]: t["Value"]
                    for t in rds.list_tags_for_resource(ResourceName=arn)["TagList"]}
            sched = SCHEDULES.get(tags.get("Schedule", ""))
            if not sched:
                continue
            ident = db["DBInstanceIdentifier"]
            status = db["DBInstanceStatus"]
            if _in_window(sched, now) and status == "stopped":
                rds.start_db_instance(DBInstanceIdentifier=ident)
                actions.append(f"start rds {ident}")
            elif not _in_window(sched, now) and status == "available":
                rds.stop_db_instance(DBInstanceIdentifier=ident)
                actions.append(f"stop rds {ident}")

    print(json.dumps({"time": now.isoformat(), "actions": actions}))
    return {"actions": actions}
'''


def _render_schedules_hcl(schedules: dict[str, dict[str, Any]]) -> str:
    lines = []
    for name, spec in sorted(schedules.items()):
        days = ", ".join(str(d) for d in spec["days"])
        lines.append(
            f'    "{name}" = {{ days = [{days}], start = {spec["start"]}, stop = {spec["stop"]} }}'
        )
    return "\n".join(lines)


def render_scheduler_tf(schedules: dict[str, dict[str, Any]], timezone: str = "UTC") -> str:
    return f'''# finops instance scheduler — generated by finops-mcp.
# Starts/stops EC2 and RDS instances whose `Schedule` tag matches a window
# defined below. Review, adjust schedules/timezone as needed, then apply.

locals {{
  finops_schedules = {{
{_render_schedules_hcl(schedules)}
  }}
}}

data "archive_file" "finops_scheduler" {{
  type        = "zip"
  source_file = "${{path.module}}/{MANAGED_LAMBDA_FILE}"
  output_path = "${{path.module}}/.finops/{MANAGED_LAMBDA_FILE}.zip"
}}

resource "aws_iam_role" "finops_scheduler" {{
  name = "{LAMBDA_FUNCTION_NAME}"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = {{ Service = "lambda.amazonaws.com" }}
    }}]
  }})
}}

resource "aws_iam_role_policy" "finops_scheduler" {{
  name = "{LAMBDA_FUNCTION_NAME}"
  role = aws_iam_role.finops_scheduler.id

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Effect = "Allow"
        Action = [
          "ec2:DescribeInstances",
          "ec2:StartInstances",
          "ec2:StopInstances",
          "rds:DescribeDBInstances",
          "rds:ListTagsForResource",
          "rds:StartDBInstance",
          "rds:StopDBInstance",
        ]
        Resource = "*"
      }},
      {{
        Effect   = "Allow"
        Action   = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"]
        Resource = "arn:aws:logs:*:*:*"
      }},
    ]
  }})
}}

resource "aws_lambda_function" "finops_scheduler" {{
  function_name    = "{LAMBDA_FUNCTION_NAME}"
  role             = aws_iam_role.finops_scheduler.arn
  runtime          = "python3.12"
  handler          = "{MANAGED_LAMBDA_FILE.removesuffix('.py')}.handler"
  filename         = data.archive_file.finops_scheduler.output_path
  source_code_hash = data.archive_file.finops_scheduler.output_base64sha256
  timeout          = 120

  environment {{
    variables = {{
      SCHEDULES_JSON = jsonencode(local.finops_schedules)
      SCHEDULER_TZ   = "{timezone}"
    }}
  }}
}}

resource "aws_cloudwatch_event_rule" "finops_scheduler" {{
  name                = "{LAMBDA_FUNCTION_NAME}"
  schedule_expression = "rate(15 minutes)"
}}

resource "aws_cloudwatch_event_target" "finops_scheduler" {{
  rule = aws_cloudwatch_event_rule.finops_scheduler.name
  arn  = aws_lambda_function.finops_scheduler.arn
}}

resource "aws_lambda_permission" "finops_scheduler" {{
  statement_id  = "AllowEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.finops_scheduler.function_name
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.finops_scheduler.arn
}}
'''


def generate_bootstrap_files(
    repo_path: str,
    schedule_names: list[str],
    timezone: str = "UTC",
) -> list[dict[str, Any]]:
    """Write the scheduler Terraform + Lambda source as new files in the repo.
    Refuses to overwrite existing files unless they were finops-generated."""
    schedules = {}
    for name in schedule_names:
        spec = parse_schedule_name(name)
        if not spec:
            raise ValueError(
                f"invalid schedule name '{name}' (expected mon-fri-HH-HH, daily-HH-HH, or sat-sun-HH-HH)"
            )
        schedules[name] = spec
    if not schedules:
        raise ValueError("no valid schedules to define")

    changes = []
    for filename, content in (
        (MANAGED_TF_FILE, render_scheduler_tf(schedules, timezone)),
        (MANAGED_LAMBDA_FILE, LAMBDA_SOURCE),
    ):
        path = os.path.join(repo_path, filename)
        existed = os.path.exists(path)
        if existed:
            head = open(path, encoding="utf-8").read(400)
            if "finops" not in head.lower():
                raise ValueError(
                    f"{filename} already exists and does not look finops-generated; refusing to overwrite"
                )
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        changes.append({
            "file": path,
            "line": 1,
            "old": "(updated)" if existed else "(new file)",
            "new": f"{filename} ({len(content.splitlines())} lines)",
            "changed": True,
        })
    return changes
